// Generate TS types from the contract's JSON Schema — the single source of truth is the Pydantic
// models in packages/contract (exported to packages/contract/schema/*.json via `make schema`).
// We DON'T hand-duplicate those shapes; run `pnpm run types` after the schema changes.
//
// Each schema compiles to its own module under src/lib/contract/ (so the shared $defs they each
// re-emit — Card, SlotOption, title aliases — stay in separate module scopes and never collide).
// contract.gen.ts then re-exports the canonical, de-duplicated set the app imports.
//
// Note: the decision trace is dict[str, Any] on the backend (untyped by design), so it is NOT in
// the schema — its shape is hand-typed in src/lib/trace.ts, with a comment saying why.
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compileFromFile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemaDir = resolve(here, "../../../packages/contract/schema");
const outDir = resolve(here, "../src/lib/contract");
const indexFile = resolve(here, "../src/lib/contract.gen.ts");

const banner = (src) =>
  `// AUTO-GENERATED from packages/contract/schema/${src} — DO NOT EDIT.\n` +
  `// Regenerate with: pnpm run types  (after \`make schema\` in the repo root).\n/* eslint-disable */\n\n`;

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const files = readdirSync(schemaDir).filter((f) => f.endsWith(".json"));
for (const f of files) {
  const ts = await compileFromFile(join(schemaDir, f), {
    bannerComment: "",
    additionalProperties: false,
    style: { singleQuote: false },
  });
  writeFileSync(join(outDir, `${basename(f, ".json")}.ts`), banner(f) + ts, "utf8");
}

// Curated, de-duplicated re-export surface the app imports from "@/lib/contract.gen".
const index =
  `// AUTO-GENERATED by scripts/gen-types.mjs — DO NOT EDIT.\n/* eslint-disable */\n\n` +
  `export type { CaseView, Card, SlotOption } from "./contract/CaseView";\n` +
  `export type { AppointmentAtRisk, Reason } from "./contract/AppointmentAtRisk";\n`;
writeFileSync(indexFile, index, "utf8");
console.log(`contract types -> ${outDir} (${files.length} schemas) + contract.gen.ts`);
